-- AlterTable companies — settings fields
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "taxId" TEXT;
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "email" TEXT;
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "postalCode" TEXT;
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "country" TEXT DEFAULT 'ES';
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "defaultTaxRate" DECIMAL(5,2) NOT NULL DEFAULT 21;
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'EUR';
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "orderPrefix" TEXT NOT NULL DEFAULT 'PED';
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "invoicePrefix" TEXT NOT NULL DEFAULT 'FAC';
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "quotePrefix" TEXT NOT NULL DEFAULT 'PRE';
ALTER TABLE "companies" ADD COLUMN IF NOT EXISTS "poPrefix" TEXT NOT NULL DEFAULT 'OC';
